version: "3.1"
services:
        web:
                image: 127.0.0.1:5000/appsec_report4
                build: .
                ports:
                        - "8080:8080"
                container_name: "flask-app"
                secrets:
                        - admin_pass
                        - csrf_token
                deploy:
                        mode: replicated
                        replicas: 4
                        resources:
                                limits:
                                        cpus: '0.50'
                                        memory: 200M
                        restart_policy:
                                condition: on-failure
secrets:
        admin_pass: 
                external: true
        csrf_token: 
                external: true
